package deadbycube.util;

public class DBDSounds {

    public static final String
            BARREL_LOOP = "barrel.loop",
            BASEMENT_FIRE_LOOP = "basement.fire.loop",
            CAMPFIRE_LOOP = "campfire.loop",
            GENERATOR_EXPLODE = "generator.explode",
            GENERATOR_PISTON = "generator.piston",
            GENERATOR_PISTON_COMPRESS = "generator.piston.compress",
            GENERATOR_PISTON_METAL = "generator.piston.metal",
            GENERATOR_PUNCH = "generator.punch",
            GENERATOR_REPAIR_CRANK = "generator.repair.crank",
            GENERATOR_REPAIR_ELECTRIC = "generator.repair.electric",
            GENERATOR_REPAIR_PULL = "generator.repair.pull",
            GENERATOR_REPAIR_PUSH = "generator.repair.push",
            GENERATOR_REPAIRED = "generator.repaired",
            GENERATOR_REPAIRED_LOOP = "generator.repaired.loop",
            GENERATOR_SPARK_LONG = "generator.spark.long",
            GENERATOR_START_FAIL = "generator.start.fail",
            GENERATOR_START_MECHANIC = "generator.start.mechanic",
            KILLER_DOCTOR_ATTACK = "killer.doctor.attack",
            KILLER_DOCTOR_ATTACK_READY = "killer.doctor.attack.ready",
            KILLER_DOCTOR_CHARGE = "killer.doctor.charge",
            KILLER_DOCTOR_CHARGE_BASS = "killer.doctor.charge.bass",
            KILLER_DOCTOR_CHARGE_HIGH = "killer.doctor.charge.high",
            KILLER_DOCTOR_LAUGH = "killer.doctor.laugh",
            KILLER_DOCTOR_STUN = "killer.doctor.stun",
            KILLER_NURSE_BLINK_APPEAR = "killer.nurse.blink.appear",
            KILLER_NURSE_BLINK_CHARGE = "killer.nurse.blink.charge",
            KILLER_NURSE_BLINK_CHARGE_FULL = "killer.nurse.blink.charge.full",
            KILLER_NURSE_BLINK_DISAPPEAR = "killer.nurse.blink.disappear",
            KILLER_NURSE_STUN = "killer.nurse.stun",
            KILLER_NURSE_TELEPORT_APPEAR = "killer.nurse.teleport.appear",
            KILLER_NURSE_TELEPORT_DISAPPEAR = "killer.nurse.teleport.disappear",
            KILLER_NURSE_TELEPORT_CHARGING = "killer.nurse.teleport.charging",
            KILLER_SHAPE_STALK_WARNING = "killer.shape.stalk.warning",
            KILLER_SHAPE_STALK_LEVEL_1 = "killer.shape.stalk.level.1",
            KILLER_SHAPE_STALK_LEVEL_2 = "killer.shape.stalk.level.2",
            KILLER_SHAPE_STALK_LEVEL_3 = "killer.shape.stalk.level.3",
            KILLER_SHAPE_STUN = "killer.shape.stun",
            KILLER_WRAITH_BELL_SINGLE = "killer.wraith.bell.single",
            KILLER_WRAITH_INVISIBILITY_ON = "killer.wraith.invisibility.on",
            KILLER_WRAITH_INVISIBILITY_OFF = "killer.wraith.invisibility.off",
            KILLER_WRAITH_STUN = "killer.wraith.stun";

}
