name: DeadByCube
description: Dead by Daylight like in Minecraft
main: deadbycube.DeadByCube
version: 0.1
author: Fabien
commands:
  role:
    description: Set your role
    usage: /role <survivor|killer|list>
  game:
    description: Game
    usage: /game <start|stop>
  structure:
    description: Description
    usage: /structure