name: DeadByCube
description: Dead by Daylight like in Minecraft
author: Fabien
version: 0.1
main: deadbycube.DeadByCube
depend: [ProtocolLib]
commands:
  debug:
    description: debug
    usage: /debug
  role:
    description: Set your role
    usage: /role <set|survivor|killer|list>
  game:
    description: Manage game
    usage: /game <start|stop|option>
  structure:
    description: Manage structure
    usage: /structure
  generator:
    description: Generator
    usage: /generator