name: DeadByCube
description: Dead by Daylight like in Minecraft
main: deadbycube.DeadByCube
version: 0.1
author: Fabien
commands:
  role:
    description: Set your role
    usage: /role <set|survivor|killer|list>
  game:
    description: Manage game
    usage: /game <start|stop|option>
  structure:
    description: Manage structure
    usage: /structure
  heartbeat:
    description: Manage survivor heartbeat
    usage: /heartbeat